# Generated by Django 6.0.7 on 2026-07-19 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ordine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("cognome", models.CharField(default="", max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("indirizzo", models.CharField(max_length=255)),
                ("citta", models.CharField(default="", max_length=100)),
                ("cap", models.CharField(default="", max_length=10)),
                ("totale", models.DecimalField(decimal_places=2, max_digits=10)),
                ("data_creazione", models.DateTimeField(auto_now_add=True)),
                (
                    "stato",
                    models.CharField(
                        choices=[
                            ("in_elaborazione", "In Elaborazione ⏳"),
                            ("spedito", "Spedito 📦"),
                            ("consegnato", "Consegnato ✅"),
                        ],
                        default="in_elaborazione",
                        max_length=20,
                    ),
                ),
                (
                    "codice_tracciamento",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Prodotto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("donna", "Donna"),
                            ("uomini", "Uomini"),
                            ("bambini", "Bambini"),
                            ("accessori", "Accessori"),
                        ],
                        default="donna",
                        max_length=20,
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("descrizione", models.TextField(blank=True, null=True)),
                ("prezzo", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "immagine",
                    models.ImageField(blank=True, null=True, upload_to="prodotti/"),
                ),
                (
                    "immagine2",
                    models.ImageField(blank=True, null=True, upload_to="prodotti/"),
                ),
                (
                    "immagine3",
                    models.ImageField(blank=True, null=True, upload_to="prodotti/"),
                ),
                (
                    "colori",
                    models.CharField(
                        blank=True,
                        help_text="Separa i colori con una virgola (es: Rosso, Blu, Nero)",
                        max_length=200,
                        null=True,
                    ),
                ),
                ("data_creazione", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Prodotto",
                "verbose_name_plural": "Prodotti",
            },
        ),
        migrations.CreateModel(
            name="VoceOrdine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantita", models.IntegerField(default=1)),
                ("prezzo", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "ordine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voci",
                        to="negozio.ordine",
                    ),
                ),
                (
                    "prodotto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="negozio.prodotto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Voce d'Ordine",
                "verbose_name_plural": "Voci d'Ordine",
            },
        ),
    ]
