# Generated by Django 6.0.7 on 2026-07-20 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("negozio", "0002_ordine_utente"),
    ]

    operations = [
        migrations.AddField(
            model_name="prodotto",
            name="quantita_disponibile",
            field=models.IntegerField(
                default=10, help_text="Quanti pezzi hai fisicamente in magazzino?"
            ),
        ),
        migrations.AlterField(
            model_name="prodotto",
            name="descrizione",
            field=models.TextField(default=10),
            preserve_default=False,
        ),
    ]
