# Generated by Django 6.0.7 on 2026-07-21 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("negozio", "0004_recensione"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsletterIscritto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("data_iscrizione", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
