# Generated by Django 6.0.7 on 2026-07-25 02:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("negozio", "0005_newsletteriscritto"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordine",
            name="stato",
            field=models.CharField(
                choices=[
                    ("PAGATO", "Pagato"),
                    ("in_elaborazione", "In Elaborazione ⏳"),
                    ("spedito", "Spedito 📦"),
                    ("consegnato", "Consegnato ✅"),
                ],
                default="in_elaborazione",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CarrelloItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(blank=True, max_length=40, null=True)),
                ("quantita", models.PositiveIntegerField(default=1)),
                ("data_aggiunta", models.DateTimeField(auto_now_add=True)),
                (
                    "prodotto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="negozio.prodotto",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
