# Generated by Django 6.0.7 on 2026-07-25 02:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("negozio", "0006_alter_ordine_stato_carrelloitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codice", models.CharField(max_length=50, unique=True)),
                ("valido_da", models.DateTimeField()),
                ("valido_a", models.DateTimeField()),
                (
                    "sconto",
                    models.IntegerField(
                        help_text="Percentuale di sconto (da 0 a 100)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("attivo", models.BooleanField(default=True)),
            ],
        ),
    ]
