# Generated by Django 6.0.7 on 2026-07-26 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("negozio", "0008_profiloutente"),
    ]

    operations = [
        migrations.AddField(
            model_name="recensione",
            name="immagine",
            field=models.ImageField(blank=True, null=True, upload_to="recensioni/"),
        ),
    ]
